package models

// Generated by https://quicktype.io

type AzureErrorResponse struct {
	Error AzureError `json:"error"`
}

type AzureError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}
