package models

// Generated by https://quicktype.io

type AzureDNSZone struct {
	ID         string                 `json:"id"`
	Name       string                 `json:"name"`
	Type       string                 `json:"type"`
	Etag       string                 `json:"etag"`
	Location   string                 `json:"location"`
	Tags       AzureTags              `json:"tags"`
	Properties AzureDNSZoneProperties `json:"properties"`
}

type AzureDNSZoneProperties struct {
	MaxNumberOfRecordSets          int64       `json:"maxNumberOfRecordSets"`
	MaxNumberOfRecordsPerRecordSet interface{} `json:"maxNumberOfRecordsPerRecordSet"`
	NameServers                    []string    `json:"nameServers"`
	NumberOfRecordSets             int64       `json:"numberOfRecordSets"`
	ZoneType                       string      `json:"zoneType"`
}

type AzureTags struct {
}

// Generated by https://quicktype.io

type AzureDNSZones struct {
	Value []AzureDNSZone `json:"value"`
}
