package models

// Generated by https://quicktype.io

type AzureDNSRecord struct {
	ID         string                   `json:"id,omitempty"`
	Name       string                   `json:"name,omitempty"`
	Type       string                   `json:"type,omitempty"`
	Etag       string                   `json:"etag,omitempty"`
	Properties AzureDnsRecordProperties `json:"properties,omitempty"`
}

type AzureDnsRecordProperties struct {
	Metadata          *AzureDnsMetadata       `json:"metadata,omitempty"`
	FQDN              string                  `json:"fqdn,omitempty"`
	TTL               int64                   `json:"TTL,omitempty"`
	TXTRecords        []AzureDnsTXTRecord     `json:"TXTRecords,omitempty"`
	ARecords          []AzureDnsARecord       `json:"ARecords,omitempty"`
	AAAARecords       []AzureDnsAAAARecord    `json:"AAAARecords,omitempty"`
	MXRecords         []AzureDnsMXRecord      `json:"MXRecords,omitempty"`
	SRVRecords        []AzureDnsSRVRecord     `json:"SRVRecords,omitempty"`
	CNAMERecord       *AzureDnsCNAMERecord    `json:"CNAMERecord,omitempty"`
	TargetResource    *AzureDnsTargetResource `json:"targetResource,omitempty"`
	ProvisioningState string                  `json:"provisioningState,omitempty"`
}

type AzureDnsARecord struct {
	Ipv4Address string `json:"ipv4Address,omitempty"`
}

type AzureDnsMXRecord struct {
	Exchange   string `json:"exchange,omitempty"`
	Preference int64  `json:"preference,omitempty"`
}

type AzureDnsAAAARecord struct {
	Ipv6Address string `json:"ipv6Address,omitempty"`
}

type AzureDnsTXTRecord struct {
	Value []string `json:"value,omitempty"`
}

type AzureDnsSRVRecord struct {
	Port     int64  `json:"port,omitempty"`
	Priority int64  `json:"priority,omitempty"`
	Target   string `json:"target,omitempty"`
	Weight   int64  `json:"weight,omitempty"`
}

type AzureDnsCNAMERecord struct {
	Cname string `json:"cname,omitempty"`
}

type AzureDnsTargetResource struct {
}

type AzureDnsMetadata struct {
	Key1 string `json:"key1,omitempty"`
}
