package models

// Generated by https://quicktype.io

type LinodeInstanceResponse struct {
	Data    []LinodeInstance `json:"data"`
	Page    int64            `json:"page"`
	Pages   int64            `json:"pages"`
	Results int64            `json:"results"`
}

type LinodeInstance struct {
	ID              int64                 `json:"id"`
	Label           string                `json:"label"`
	Group           string                `json:"group"`
	Status          string                `json:"status"`
	Created         string                `json:"created"`
	Updated         string                `json:"updated"`
	Type            string                `json:"type"`
	Ipv4            []string              `json:"ipv4"`
	Ipv6            string                `json:"ipv6"`
	Image           string                `json:"image"`
	Region          string                `json:"region"`
	Specs           LinodeInstanceSpecs   `json:"specs"`
	Alerts          LinodeInstanceAlerts  `json:"alerts"`
	Backups         LinodeInstanceBackups `json:"backups"`
	Hypervisor      string                `json:"hypervisor"`
	WatchdogEnabled bool                  `json:"watchdog_enabled"`
	Tags            []string              `json:"tags"`
}

type LinodeInstanceAlerts struct {
	CPU           int64 `json:"cpu"`
	NetworkIn     int64 `json:"network_in"`
	NetworkOut    int64 `json:"network_out"`
	TransferQuota int64 `json:"transfer_quota"`
	Io            int64 `json:"io"`
}

type LinodeInstanceBackups struct {
	Enabled        bool                   `json:"enabled"`
	Schedule       LinodeInstanceSchedule `json:"schedule"`
	LastSuccessful interface{}            `json:"last_successful"`
}

type LinodeInstanceSchedule struct {
	Day    interface{} `json:"day"`
	Window interface{} `json:"window"`
}

type LinodeInstanceSpecs struct {
	Disk     int64 `json:"disk"`
	Memory   int64 `json:"memory"`
	Vcpus    int64 `json:"vcpus"`
	Gpus     int64 `json:"gpus"`
	Transfer int64 `json:"transfer"`
}
